<?php

return [
    // Page Titles
    'page_title' => 'Employee Data',
    'employee_detail' => 'Employee Detail',
    'preview_export_pdf_title' => 'Preview Export PDF',
    
    // Navigation
    'back_to_list' => 'Back to Employee List',
    'back_to_detail' => 'Back to Employee Detail',
    
    // Summary Section
    'total_employees' => 'Employees',
    'total_registered' => 'Total employees registered in the system',
    'employee_pgb' => 'PGB Employees',
    'licensing_pkj' => 'PKJ Licensing',
    
    // Employee Info
    'section' => 'Section',
    'employee' => 'Employee',
    'licensing' => 'Licensing',
    'employee_information' => 'Employee Information',
    'full_name' => 'Full Name',
    'email' => 'Email',
    'role' => 'Role',
    'employee_pgb_role' => 'PGB Employee',
    'licensing_pkj_role' => 'PKJ Licensing',
    
    // Stats
    'projects' => 'Projects',
    'activities' => 'Activities',
    'all_activities' => 'All Activities', // NEW
    'activity_breakdown' => 'Activity Breakdown', // NEW
    'activities_by_status' => 'Activities by Status', // NEW
    'completion_rate' => 'Completion Rate',
    'total_projects' => 'Total Projects',
    'total_activities' => 'Total Activities',
    'performance_summary' => 'Performance Summary',
    
    // Activity Status Details
    'done_activities' => 'Done', // NEW
    'progress_activities' => 'In Progress', // NEW
    'pending_activities' => 'Pending', // NEW
    
    // Table Headers
    'no' => 'No',
    'project_name' => 'Project Name',
    'status' => 'Status',
    'start_date' => 'Start Date',
    'deadline' => 'Deadline',
    'actions' => 'Actions',
    'projects_list' => 'Projects List',
    
    // Status
    'completed' => 'Completed',
    'in_progress' => 'In Progress',
    'pending' => 'Pending',
    
    // Activities Count
    'activity_count' => 'activities',
    'completed_count' => 'completed',
    
    // Buttons
    'view_detail' => 'View Detail',
    'preview_export_pdf' => 'Preview Export PDF',
    'download_pdf_now' => 'Download PDF Now',
    'back' => 'Back',
    
    // Empty States
    'no_employees' => 'No Employee Data',
    'no_employees_desc' => 'No employees are registered in the system yet.',
    'no_projects' => 'No projects being worked on yet',
    'no_projects_assigned' => 'No assigned projects',
    
    // Projects Section
    'projects_worked_on' => 'Projects Worked On',
    
    // Export Preview
    'performance_report' => 'EMPLOYEE PERFORMANCE REPORT',
    'bank_name' => 'Bank Pembangunan Daerah Bali',
    'period' => 'Period',
    'preview_info' => 'This is a preview of the document to be exported. Click the <strong>"Download PDF Now"</strong> button to download the PDF file.',
    'document_footer' => 'This document is automatically generated by the WorkLog system - Bank BPD Bali',
    'generated_date' => 'Generated Date',

    'employee_pgb'        => 'PGB Employee',
    'employee_pgb_role'   => 'PGB Employee',
    'kabag_pgb_role'      => 'PGB Head of Section',
    'licensing_pkj'       => 'PKJ Licensing',
    'licensing_pkj_role'  => 'PKJ Head of Licensing',

    // Search & Filter
    'search_placeholder' => 'Search employee name or email...',
    'all_sections' => 'All Sections',
    'all_roles' => 'All Roles',
    'reset' => 'Reset',

    // Header Counter
    'employees' => 'Employees',
    'pgb_employee' => 'PGB Employees',
    'pkj_licensing' => 'PKJ Licensing',
    'pkj_employee' => 'PKJ Employees',

    // Role Labels (untuk multi-bahasa)
    'kabag_pgb' => 'Head of PGB',
    'kabag_pkj' => 'Head of PKJ',

];